### PR TITLE
Updates for kwin 5.24

### PR DESCRIPTION
**Pull request by aleasto**

### CODE REVIEW

**Comment by ryu-ketsueki** [comment]
You may want to rebase that on 5.24.1. I can't build anymore

**Review by RocketKevQt — APPROVED** [review]

**Comment by p0ryae** [comment]
Works very well!
OP pls accept the pr

**Comment by ryu-ketsueki** [comment]
> Works very well! OP pls accept the pr

Not for me on Plasma 5.24.2

**Comment by p0ryae** [comment]
Just compile it when switching to this pr

Make sure to do chmod +x

**Comment by ryu-ketsueki** [comment]
> Just compile it when switching to this pr
> 
> Make sure to do chmod +x

It doesn't compile. Already opened an issue

**Comment by ryu-ketsueki** [comment]
I had both of them cloned and installed the unmerged one by accident. Just built with the correct one and it is working

**Comment by p0ryae** [comment]
> I had both of them cloned and installed the unmerged one by accident. Just built with the correct one and it is working

I wonder why the dev isnt active

**Comment by Alban-Boissard** [comment]
Thank you for the work !

PS : I apologize for my absence, I was very busy the last month.

**Pull request merged**
